name: Excel Upload Workflow

on:
  push:
    paths:
      - 'files/*.xlsx'

permissions: 
  issues: write
  contents: read

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('.github/actions/package-lock.json') }}

      - name: Install Node Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cat .github/actions/package.json > package.json
          cat .github/actions/package-lock.json > package-lock.json
          npm ci

      - name: Do Action
        id: do-action
        uses: ./.github/actions/get-commit-file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print output
        run: |
          echo "Output: ${{ steps.do-action.outputs.files }}"
